[package]
name = "rusteditor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["tokio", "highlighter"]}
iced_aw = "0.12.2"
rfd = "0.15.4"
tokio = {version = "1.47.1", features = ["full"] }
